<img src="../../img/ICHEC_Logo.png" alt="Drawing" style="width: 500px;"/>


# <center> Exercises

******
# <center> <b>Performance Measurement</b>
    
### <center> 10 minutes
******
#### <center> <b>Exercise 1<b/>

There are three functions in the code block below. Each is a slightly different implementation of a Montecarlo algorithm for calculating the value of pi. Use `time.time()`, `%timeit`, `cProfile` and `pstats` to learn how the functions work. Are the timings what you would expect? What implementation is fastest for 1 million points?

<br>

`pi_estimation_pure()` is a pure Python implementation using lists

`pi_estimation_loop()` uses numpy arrays to replace the python lists.

`pi_estimation_np()` uses numpy to improve the performance of the algorithm. 

<br>

**Hint:** You may want to try writing the three functions to a file and running `cProfile` on that file. You can use the ipython magic `%%writefile`

In [1]:
import math
import random as rnd
import numpy as np
import time

def pi_estimation_pure(n):
    # Using time.time()
    t0 = time.time()
    x, y = [], []
    for i in range(n):
        x.append(rnd.random())
        y.append(rnd.random())
    pi_xy = [(x[i], y[i]) for i in range(n) if math.sqrt(x[i] ** 2 + y[i] ** 2) <= 1]
    # Using time.time()
    t1 = time.time()
    print(t1-t0)
    return 4 * len(pi_xy) / len(x)

def pi_estimation_loop(n):
    count=0
    # Using time.time()
    t2 = time.time()
    for step in range(n):
        x=np.random.rand(1)
        y=np.random.rand(1)
        if math.sqrt(x*x+y*y)<1:
            count+=1
    # Using time.time()
    t3 = time.time()
    print(t3-t2)
    return 4*count/n

def pi_estimation_np(n):
    # Using time.time()
    t4 = time.time()
    p=np.random.rand(n,2)
    p_est = 4*np.sum(np.sqrt(p[:,0]*p[:,0]+p[:,1]*p[:,1])<1)/n
    # Using time.time()
    t5 = time.time()
    print(t5-t4)
    return p_est

In [2]:
pi_estimation_pure(1000000)

0.7457091808319092


3.142828

In [3]:
pi_estimation_loop(1000000)

3.419360876083374


3.1409

In [4]:
pi_estimation_np(1000000)

0.04009199142456055


3.146424

In [5]:
# pi_estimation_pure()
%timeit pi_estimation_pure(1000000)

0.6388969421386719
0.6404180526733398
0.6299540996551514
0.6413071155548096
0.6320500373840332
0.6311459541320801
0.638883113861084
0.6296782493591309
686 ms ± 4.52 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
# pi_estimation_loop()
%timeit pi_estimation_loop(1000000)

3.458165168762207
3.5930898189544678
3.5071208477020264
3.507952928543091
3.4211158752441406
3.581799030303955
3.7002501487731934
3.5380139350891113
3.55 s ± 80.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
# pi_estimation_np()
%timeit pi_estimation_np(1000000)

0.03532910346984863
0.019591093063354492
0.021593809127807617
0.020576000213623047
0.020442724227905273
0.021185874938964844
0.02086186408996582
0.020165205001831055
0.021763086318969727
0.023832082748413086
0.023051977157592773
0.020264863967895508
0.02056717872619629
0.020463228225708008
0.021265268325805664
0.02032303810119629
0.020058870315551758
0.021752119064331055
0.022140979766845703
0.02025127410888672
0.02091217041015625
0.0202181339263916
0.019881010055541992
0.02109217643737793
0.020277976989746094
0.019812822341918945
0.02013707160949707
0.019914627075195312
0.02050495147705078
0.020180940628051758
0.020965099334716797
0.01991128921508789
0.019964933395385742
0.020548105239868164
0.020367145538330078
0.020576000213623047
0.02005791664123535
0.020261287689208984
0.019858360290527344
0.020518064498901367
0.020605087280273438
0.019870996475219727
0.02013373374938965
0.021491050720214844
0.020427227020263672
0.0203249454498291
0.020351886749267578
0.02017521858215332
0.0203332

****


#### <center> <b>Exercise 2

The file **heat_equation_simple.py** contains an inefficient implementation of the two dimensional heat equation. Use cProfile and pstats to find where the time is most spent in the program (did in class)

* Compare with the file **heat_equation_index.py** a more efficient version that uses indexing rather than for loops.

In [8]:
!python -m cProfile -o heat_equation_simple.prof heat_equation_simple.py

Running Time: 19.337878942489624


In [9]:
!python -m cProfile -o heat_equation_index.prof heat_equation_index.py

Running Time: 0.0661311149597168


In [10]:
from pstats import Stats
p1 = Stats('heat_equation_simple.prof')
p2 = Stats('heat_equation_index.prof')

p1.strip_dirs() 
p2.strip_dirs() 

p1.sort_stats('cumulative').print_stats(10)
p2.sort_stats('cumulative').print_stats(10)

Tue May 10 10:55:01 2022    heat_equation_simple.prof

         1007137 function calls (988274 primitive calls) in 22.350 seconds

   Ordered by: cumulative time
   List reduced from 5908 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   1272/1    0.008    0.000   22.351   22.351 {built-in method builtins.exec}
        1    0.000    0.000   22.351   22.351 heat_equation_simple.py:1(<module>)
        1    0.000    0.000   19.642   19.642 heat_equation_simple.py:41(main)
        1    0.001    0.001   19.338   19.338 heat_equation_simple.py:35(iterate)
      200   19.337    0.097   19.337    0.097 evolve.py:1(evolve)
       83    0.004    0.000    6.032    0.073 __init__.py:1(<module>)
    912/6    0.008    0.000    2.752    0.459 <frozen importlib._bootstrap>:986(_find_and_load)
    909/6    0.005    0.000    2.752    0.459 <frozen importlib._bootstrap>:956(_find_and_load_unlocked)
    871/7    0.006    0.000    2.750    0.393 <froz

*****
*****

# <center> <b>NumPy</b>
    
### <center> 5 minutes
****
#### <center> <b> Exercise 1

Create arrays of zeros using `np.zeros`, then use slicing to obtain the following outputs:

A
$$\begin{bmatrix} 0 & 0 & 0 & 0 \\ 2 & 2 & 2 & 2 \\ 2 & 2 & 2 & 2 \\ 0 & 0 & 0 & 0 \end{bmatrix}$$
B
$$\begin{bmatrix} 0 & 0 & 0 & 0 \\ 0 & 2 & 2 & 0 \\ 0 & 2 & 2 & 0 \\ 0 & 0 & 0 & 0 \end{bmatrix}$$
C
$$\begin{bmatrix} 2 & 2 & 2 & 2 \\ 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 \\ 2 & 2 & 2 & 2 \end{bmatrix}$$
D
$$\begin{bmatrix} 2 & 0 & 0 & 2 \\ 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 \\ 2 & 0 & 0 & 2 \end{bmatrix}$$

In [11]:
import numpy as np

In [12]:
# A
a = np.zeros((4,4))
a[1:3, :] = 2
a

array([[0., 0., 0., 0.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [0., 0., 0., 0.]])

In [13]:
# B
b = np.zeros((4,4))
b[1:3, 1:3] = 2
b

array([[0., 0., 0., 0.],
       [0., 2., 2., 0.],
       [0., 2., 2., 0.],
       [0., 0., 0., 0.]])

In [14]:
# C
c = np.zeros((4,4))
c[0:4:3, 0:] = 2
c

array([[2., 2., 2., 2.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [2., 2., 2., 2.]])

In [15]:
# D
d = np.zeros((4,4))
d[0:4:3, 0:4:3] = 2
d

array([[2., 0., 0., 2.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [2., 0., 0., 2.]])

#### <center><b> Exercise 2

Generate a sequence of the first 10000 powers of 2 in a numpy array (starting at $2^0$).
Your output should be an array $[2^0, 2^1, 2^2, 2^3, ...]$.

In [16]:
import time
#List version
ti=time.time()
outloop=[2**i for i in range(10000)]
tf=time.time()
print('List time: {} seconds'.format(tf-ti))


#Numpy version-Complete the code:
ti=time.time()
out = np.array(2**i for i in range(10000))
tf=time.time()
print('NumPy time: {} seconds'.format(tf-ti))

List time: 0.09607720375061035 seconds
NumPy time: 9.322166442871094e-05 seconds


******
******

## <center> <b> Caching</b>

### <center> 5 minutes
****

Imagine you want to determine all the different ways you can reach a specific stair in a staircase by hopping one, two, or three stairs at a time. 

How many paths are there to the fourth stair? Here are all the different combinations.

<img src="../../img/stairs.png" alt="Drawing" style="width: 500px;"/>

A solution to this problem is to state that;

<center> <b>To reach your current stair, you can jump from one stair, two stairs, or three stairs below.</b>
<br>
    <br>

Adding up the number of jump combinations you can use to get to each of those points should give you the total number of possible ways to reach your current position.

For 4 stairs, there are 7 combinations. For 3 there is 4, and for 2 there is 2.
    
The file `stairs.py` implements recursion to solve the problem

In [17]:
from functools import lru_cache
@lru_cache(100)
def steps_to(stair):
    if stair == 1:
        # You can reach the first stair with only a single step
        # from the floor.
        return 1
    elif stair == 2:
        # You can reach the second stair by jumping from the
        # floor with a single two-stair hop or by jumping a single
        # stair a couple of times.
        return 2
    elif stair == 3:
        # You can reach the third stair using four possible
        # combinations:
        # 1. Jumping all the way from the floor
        # 2. Jumping two stairs, then one
        # 3. Jumping one stair, then two
        # 4. Jumping one stair three times
        return 4
    else:
        # You can reach your current stair from three different places:
        # 1. From three stairs down
        # 2. From two stairs down
        # 2. From one stair down
        #
        # If you add up the number of ways of getting to those
        # those three positions, then you should have your solution.
        return (
            steps_to(stair - 3)
            + steps_to(stair - 2)
            + steps_to(stair - 1)
        )

print(steps_to(30))

53798080


Create a timing setup and record the time taken for **30 iterations**. Then implement the `lru_cache` and compare the improvement.

In [19]:
import timeit
t1 = timeit.Timer("steps_to(30)", "from __main__ import steps_to")
print(t1.timeit(1))

1.940000004196918e-06
